### ISSUE TITLE
[JOSS] Spack build failing

### ISSUE THREAD

**Issue by jakelangham** [SGpp/DisCoTec#132]
This issue relates to the ongoing reviews at https://github.com/openjournals/joss-reviews/issues/7018.

I was able to successfully build discotec via spack on two machines (a desktop and HPC). 

However, on another cluster, the build fails to build one of the dependencies (libevent-2.1.12) because spack can't find openssl/ssl.h. This certainly isn't discotec's fault (it turns out that header is in a slightly odd place on that system), but ultimately it does affect the installation process. Therefore, perhaps for users like me that are unfamiliar with spack, you could add a brief bit of guidance to the README about how to get spack look for things in the right places. After all, it's pretty common when building on HPC to have to do this kind of troubleshooting. (This may also be helpful for the CMake installation option too, though people are probably more familiar with CMake in general.)

**Comment by freifrauvonbleifrei** [comment]
the Spack installation is getting a bit more space in the new documentation: https://discotec.readthedocs.io/en/latest/getting_started.html , including links to the typical Spack resources. @jakelangham do you think you would know where to look based on this info? Unfortunately, resolving dependencies on HPC can be *very* complex, which is why we (and many HPC operators) try to outsource as much as possible to Spack and its documentation.

**Comment by jakelangham** [comment]
I think the new documentation is sufficient to close this. 

I got the code built on all 3 systems in the end with spack and cmake, so that feels like a decent test of the install process. FYI, I actually didn't find the spack documentation all that useful in this regard, since it seems more aimed at package developers and sysadmins than impatient users who just want to build 1 piece of software. But that is hardly your responsibility!
